// <auto-generated />
using DungeonExplorerApi.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DungeonExplorerApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251130095547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DungeonExplorerApi.Entities.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("DungeonExplorerApi.Entities.Map", b =>
                {
                    b.OwnsOne("DungeonExplorerApi.Entities.Position", "Goal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.ToTable("Maps");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("DungeonExplorerApi.Entities.Position", "Start", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.ToTable("Maps");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsMany("DungeonExplorerApi.Entities.Position", "Obstacles", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MapId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("MapId");

                            b1.ToTable("MapObstacles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MapId");
                        });

                    b.Navigation("Goal")
                        .IsRequired();

                    b.Navigation("Obstacles");

                    b.Navigation("Start")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
